############################
## CHANGE THESE
############################

baseURL: "https://www.souls-music.com"
title: "Soul's Whisper"

############################
## MODULES
############################

module:
  imports:
    - path: github.com/chrede88/L1nkr

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
